### PR TITLE
Bump development dependencies

### PR DESCRIPTION
**Pull request by Earlopain**
Older versions of prism don't build that well with recent compilers

```
Installing prism 0.24.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/earlopain/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/prism-0.24.0/ext/prism
/home/earlopain/.rbenv/versions/3.3.3/bin/ruby extconf.rb
checking for prism.h in /home/earlopain/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/prism-0.24.0/include... yes
checking for prism/extension.h in /home/earlopain/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/prism-0.24.0/ext... yes
checking for whether -fvisibility=hidden is accepted as CFLAGS... yes
compiling build/static/serialize.o
compiling build/static/encoding.o
compiling build/static/pack.o
compiling build/static/options.o
compiling build/static/token_type.o
compiling build/static/regexp.o
compiling build/static/node.o
compiling build/static/prism.o
src/prism.c: In function ‘parser_lex_magic_comment’:
src/prism.c:6776:67: error: ‘calloc’ sizes specified with ‘sizeof’ in the earlier argument and not in the later argument
[-Werror=calloc-transposed-args]
 6776 |         if ((magic_comment = (pm_magic_comment_t *) calloc(sizeof(pm_magic_comment_t), 1)) != NULL) {
      |                                                                   ^~~~~~~~~~~~~~~~~~
src/prism.c:6776:67: note: earlier argument should specify number of elements, later size of each element
src/prism.c: In function ‘parser_comment’:
src/prism.c:8208:60: error: ‘calloc’ sizes specified with ‘sizeof’ in the earlier argument and not in the later argument
[-Werror=calloc-transposed-args]
 8208 |     pm_comment_t *comment = (pm_comment_t *) calloc(sizeof(pm_comment_t), 1);
      |                                                            ^~~~~~~~~~~~
src/prism.c:8208:60: note: earlier argument should specify number of elements, later size of each element
cc1: all warnings being treated as errors
make: *** [Makefile:54: build/static/prism.o] Error 1
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
```

### CODE REVIEW

**Comment by r7kamura** [comment]
I have no objection to increasing the version, but I have tried with Ruby 3.3.3 and cannot reproduce the problem. How can I reproduce it?

**Comment by r7kamura** [comment]
I tried the following steps on my Ubuntu machine:

```
rbenv install 3.3.3
rbenv shell 3.3.3
bundle install
```

**Comment by Earlopain** [comment]
I'm not so sure but I imagine is has to do something with GCC 14 which is installed for me. Ubuntu probably hasn't pulled that one in yet. Here's the prism issue for this https://github.com/ruby/prism/issues/2645

**Comment by r7kamura** [comment]
I see, it would be a bit difficult to reproduce. Thanks anyway 👌

**Pull request merged**
